[package]
name = "ark-starknet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
starknet.workspace = true

url = "2.3.1"
regex = "1.9.1"

[features]
mock = []