[package]
name = "ark-rs"
version = "0.1.0"
edition = "2021"
authors = ["Screenshot Labs", "Starknet community"]
license = "MIT OR Apache-2.0"
readme = "README.md"
#documentation = "https://docs.rs/..."
repository = "https://github.com/TheArkProjekt/arkproject-rs"
homepage = "https://arkproject.dev"
description = """
ArkProject libraries written in Rust
"""

[workspace]
members = [
  "crates/ark-metadata",
  "crates/ark-starknet",
  "crates/ark-storage",
  "crates/ark-indexer",
]

[workspace.dependencies]
ark-starknet = { path = "./crates/ark-starknet" }
ark-metadata = { path = "./crates/ark-metadata" }
ark-storage = { path = "./crates/ark-storage" }
ark-indexer = { path = "./crates/ark-indexer" }
async-trait = "0.1.73"
starknet = "0.5.0"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }

# Thoses dependencies are used by the examples + the lib.rs.
[dependencies]
anyhow.workspace = true
tokio.workspace = true
ark-starknet.workspace = true
ark-metadata.workspace = true
ark-storage.workspace = true
ark-indexer.workspace = true
