[workspace]
members = [
  "crates/ark-collection-update-lambda",
  "crates/ark-db",
  "crates/ark-metadata",
  "crates/ark-starknet",
  "crates/ark-tables",
  "crates/ark-transfers",
  "crates/ark-stream",
  "crates/arkchain-indexer",
]

[package]
name = "ark-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
<<<<<<< HEAD
chrono = "0.4.19"
=======
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing = "0.1"
tracing-log = "0.1"
>>>>>>> c74f34f (feat(transfers): update with self for token manager & trace)
regex = "1.5.4"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
starknet = "0.5.0"
dotenv = "0.15.0"
serde = "1.0.164"
aws-config = "0.56.0"
aws-sdk-dynamodb = "0.29.0"
clap = "4.3.8"
structopt = { version = "0.3", default-features = false }
hex = "0.4.3"
aws-types = "0.56"

num-bigint = { version = "0.4.3", default-features = false }
log = "0.4"
simple_logger = "4.2.0"
ark-collection-update-lambda = { path = "./crates/ark-collection-update-lambda" }
ark-db = { path = "./crates/ark-db" }
ark-starknet = { path = "./crates/ark-starknet" }
ark-metadata = { path = "./crates/ark-metadata" }
ark-stream = { path = "./crates/ark-stream" }
ark-transfers-v2 = { path = "./crates/ark-transfers-v2" }
openssl = { version = "0.10", features = ["vendored"] }

[package.metadata.lambda.deploy]
role = "role-full-arn"       # Function's execution role
env_file = ".env.production" # File to load environment variables from
binary_name = "toto"
name = "toto"
function_name = "test"
