/**
 * This file is autogenerated by
 * You should not edit it manually or your changes might be overwritten.
 */

export default [
  {
    type: "impl",
    name: "AppchainMessagingUpgradeImpl",
    interface_name: "ark_starknet::appchain_messaging::IUpgradeable"
  },
  {
    type: "interface",
    name: "ark_starknet::appchain_messaging::IUpgradeable",
    items: [
      {
        type: "function",
        name: "upgrade",
        inputs: [
          { name: "class_hash", type: "core::starknet::class_hash::ClassHash" }
        ],
        outputs: [],
        state_mutability: "external"
      }
    ]
  },
  {
    type: "impl",
    name: "AppchainMessagingImpl",
    interface_name: "ark_starknet::appchain_messaging::IAppchainMessaging"
  },
  {
    type: "struct",
    name: "core::array::Span::<core::felt252>",
    members: [
      { name: "snapshot", type: "@core::array::Array::<core::felt252>" }
    ]
  },
  {
    type: "interface",
    name: "ark_starknet::appchain_messaging::IAppchainMessaging",
    items: [
      {
        type: "function",
        name: "update_appchain_account_address",
        inputs: [
          {
            name: "appchain_address",
            type: "core::starknet::contract_address::ContractAddress"
          }
        ],
        outputs: [],
        state_mutability: "external"
      },
      {
        type: "function",
        name: "send_message_to_appchain",
        inputs: [
          {
            name: "to_address",
            type: "core::starknet::contract_address::ContractAddress"
          },
          { name: "selector", type: "core::felt252" },
          { name: "payload", type: "core::array::Span::<core::felt252>" }
        ],
        outputs: [{ type: "(core::felt252, core::felt252)" }],
        state_mutability: "external"
      },
      {
        type: "function",
        name: "add_messages_hashes_from_appchain",
        inputs: [
          {
            name: "messages_hashes",
            type: "core::array::Span::<core::felt252>"
          }
        ],
        outputs: [],
        state_mutability: "external"
      },
      {
        type: "function",
        name: "consume_message_from_appchain",
        inputs: [
          {
            name: "from_address",
            type: "core::starknet::contract_address::ContractAddress"
          },
          { name: "payload", type: "core::array::Span::<core::felt252>" }
        ],
        outputs: [{ type: "core::felt252" }],
        state_mutability: "external"
      },
      {
        type: "function",
        name: "execute_message_from_appchain",
        inputs: [
          {
            name: "from_address",
            type: "core::starknet::contract_address::ContractAddress"
          },
          {
            name: "to_address",
            type: "core::starknet::contract_address::ContractAddress"
          },
          { name: "selector", type: "core::felt252" },
          { name: "payload", type: "core::array::Span::<core::felt252>" }
        ],
        outputs: [],
        state_mutability: "external"
      }
    ]
  },
  {
    type: "constructor",
    name: "constructor",
    inputs: [
      {
        name: "owner",
        type: "core::starknet::contract_address::ContractAddress"
      },
      {
        name: "appchain_account",
        type: "core::starknet::contract_address::ContractAddress"
      }
    ]
  },
  {
    type: "event",
    name: "ark_starknet::appchain_messaging::appchain_messaging::MessageSentToAppchain",
    kind: "struct",
    members: [
      { name: "message_hash", type: "core::felt252", kind: "key" },
      {
        name: "from",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "key"
      },
      {
        name: "to",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "key"
      },
      { name: "selector", type: "core::felt252", kind: "data" },
      { name: "nonce", type: "core::felt252", kind: "data" },
      {
        name: "payload",
        type: "core::array::Span::<core::felt252>",
        kind: "data"
      }
    ]
  },
  {
    type: "event",
    name: "ark_starknet::appchain_messaging::appchain_messaging::MessagesRegisteredFromAppchain",
    kind: "struct",
    members: [
      {
        name: "messages_hashes",
        type: "core::array::Span::<core::felt252>",
        kind: "data"
      }
    ]
  },
  {
    type: "event",
    name: "ark_starknet::appchain_messaging::appchain_messaging::MessageConsumed",
    kind: "struct",
    members: [
      { name: "message_hash", type: "core::felt252", kind: "key" },
      {
        name: "from",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "key"
      },
      {
        name: "to",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "key"
      },
      {
        name: "payload",
        type: "core::array::Span::<core::felt252>",
        kind: "data"
      }
    ]
  },
  {
    type: "event",
    name: "ark_starknet::appchain_messaging::appchain_messaging::MessageExecuted",
    kind: "struct",
    members: [
      {
        name: "from_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "key"
      },
      {
        name: "to_address",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "key"
      },
      { name: "selector", type: "core::felt252", kind: "key" },
      {
        name: "payload",
        type: "core::array::Span::<core::felt252>",
        kind: "data"
      }
    ]
  },
  {
    type: "event",
    name: "ark_starknet::appchain_messaging::appchain_messaging::Upgraded",
    kind: "struct",
    members: [
      {
        name: "class_hash",
        type: "core::starknet::class_hash::ClassHash",
        kind: "data"
      }
    ]
  },
  {
    type: "event",
    name: "ark_starknet::appchain_messaging::appchain_messaging::Event",
    kind: "enum",
    variants: [
      {
        name: "MessageSentToAppchain",
        type: "ark_starknet::appchain_messaging::appchain_messaging::MessageSentToAppchain",
        kind: "nested"
      },
      {
        name: "MessagesRegisteredFromAppchain",
        type: "ark_starknet::appchain_messaging::appchain_messaging::MessagesRegisteredFromAppchain",
        kind: "nested"
      },
      {
        name: "MessageConsumed",
        type: "ark_starknet::appchain_messaging::appchain_messaging::MessageConsumed",
        kind: "nested"
      },
      {
        name: "MessageExecuted",
        type: "ark_starknet::appchain_messaging::appchain_messaging::MessageExecuted",
        kind: "nested"
      },
      {
        name: "Upgraded",
        type: "ark_starknet::appchain_messaging::appchain_messaging::Upgraded",
        kind: "nested"
      }
    ]
  }
] as const;
