/**
 * This file is autogenerated by
 * You should not edit it manually or your changes might be overwritten.
 */

export default [
  {
    type: "impl",
    name: "ExecutorImpl",
    interface_name: "ark_starknet::interfaces::IExecutor",
  },
  {
    type: "enum",
    name: "core::option::Option::<core::felt252>",
    variants: [
      { name: "Some", type: "core::felt252" },
      { name: "None", type: "()" },
    ],
  },
  {
    type: "struct",
    name: "core::integer::u256",
    members: [
      { name: "low", type: "core::integer::u128" },
      { name: "high", type: "core::integer::u128" },
    ],
  },
  {
    type: "enum",
    name: "core::option::Option::<core::integer::u256>",
    variants: [
      { name: "Some", type: "core::integer::u256" },
      { name: "None", type: "()" },
    ],
  },
  {
    type: "struct",
    name: "ark_common::protocol::order_types::FulfillInfo",
    members: [
      { name: "order_hash", type: "core::felt252" },
      {
        name: "related_order_hash",
        type: "core::option::Option::<core::felt252>",
      },
      {
        name: "fulfiller",
        type: "core::starknet::contract_address::ContractAddress",
      },
      { name: "token_chain_id", type: "core::felt252" },
      {
        name: "token_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      { name: "token_id", type: "core::option::Option::<core::integer::u256>" },
      {
        name: "fulfill_broker_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
  },
  {
    type: "struct",
    name: "ark_common::protocol::order_types::CancelInfo",
    members: [
      { name: "order_hash", type: "core::felt252" },
      {
        name: "canceller",
        type: "core::starknet::contract_address::ContractAddress",
      },
      { name: "token_chain_id", type: "core::felt252" },
      {
        name: "token_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      { name: "token_id", type: "core::option::Option::<core::integer::u256>" },
    ],
  },
  {
    type: "enum",
    name: "ark_common::protocol::order_types::RouteType",
    variants: [
      { name: "Erc20ToErc721", type: "()" },
      { name: "Erc721ToErc20", type: "()" },
    ],
  },
  {
    type: "struct",
    name: "core::array::Span::<core::felt252>",
    members: [
      { name: "snapshot", type: "@core::array::Array::<core::felt252>" },
    ],
  },
  {
    type: "struct",
    name: "ark_common::protocol::order_v1::OrderV1",
    members: [
      { name: "route", type: "ark_common::protocol::order_types::RouteType" },
      {
        name: "currency_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      { name: "currency_chain_id", type: "core::felt252" },
      { name: "salt", type: "core::felt252" },
      {
        name: "offerer",
        type: "core::starknet::contract_address::ContractAddress",
      },
      { name: "token_chain_id", type: "core::felt252" },
      {
        name: "token_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      { name: "token_id", type: "core::option::Option::<core::integer::u256>" },
      { name: "quantity", type: "core::integer::u256" },
      { name: "start_amount", type: "core::integer::u256" },
      { name: "end_amount", type: "core::integer::u256" },
      { name: "start_date", type: "core::integer::u64" },
      { name: "end_date", type: "core::integer::u64" },
      {
        name: "broker_id",
        type: "core::starknet::contract_address::ContractAddress",
      },
      { name: "additional_data", type: "core::array::Span::<core::felt252>" },
    ],
  },
  {
    type: "struct",
    name: "ark_common::protocol::order_types::ExecutionInfo",
    members: [
      { name: "order_hash", type: "core::felt252" },
      {
        name: "nft_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "nft_from",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "nft_to",
        type: "core::starknet::contract_address::ContractAddress",
      },
      { name: "nft_token_id", type: "core::integer::u256" },
      {
        name: "payment_from",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "payment_to",
        type: "core::starknet::contract_address::ContractAddress",
      },
      { name: "payment_amount", type: "core::integer::u256" },
      {
        name: "payment_currency_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      { name: "payment_currency_chain_id", type: "core::felt252" },
      {
        name: "listing_broker_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "fulfill_broker_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
    ],
  },
  {
    type: "struct",
    name: "ark_oz::erc2981::fees::FeesRatio",
    members: [
      { name: "numerator", type: "core::integer::u256" },
      { name: "denominator", type: "core::integer::u256" },
    ],
  },
  {
    type: "struct",
    name: "ark_starknet::interfaces::FeesAmount",
    members: [
      { name: "fulfill_broker", type: "core::integer::u256" },
      { name: "listing_broker", type: "core::integer::u256" },
      { name: "ark", type: "core::integer::u256" },
      { name: "creator", type: "core::integer::u256" },
    ],
  },
  {
    type: "interface",
    name: "ark_starknet::interfaces::IExecutor",
    items: [
      {
        type: "function",
        name: "fulfill_order",
        inputs: [
          {
            name: "fulfillInfo",
            type: "ark_common::protocol::order_types::FulfillInfo",
          },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "cancel_order",
        inputs: [
          {
            name: "cancelInfo",
            type: "ark_common::protocol::order_types::CancelInfo",
          },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "create_order",
        inputs: [
          { name: "order", type: "ark_common::protocol::order_v1::OrderV1" },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "execute_order",
        inputs: [
          {
            name: "execution_info",
            type: "ark_common::protocol::order_types::ExecutionInfo",
          },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "update_admin_address",
        inputs: [
          {
            name: "admin_address",
            type: "core::starknet::contract_address::ContractAddress",
          },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "update_orderbook_address",
        inputs: [
          {
            name: "orderbook_address",
            type: "core::starknet::contract_address::ContractAddress",
          },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "update_eth_address",
        inputs: [
          {
            name: "eth_address",
            type: "core::starknet::contract_address::ContractAddress",
          },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "update_messaging_address",
        inputs: [
          {
            name: "msger_address",
            type: "core::starknet::contract_address::ContractAddress",
          },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "get_messaging_address",
        inputs: [],
        outputs: [
          { type: "core::starknet::contract_address::ContractAddress" },
        ],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "get_orderbook_address",
        inputs: [],
        outputs: [
          { type: "core::starknet::contract_address::ContractAddress" },
        ],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "update_arkchain_orderbook_address",
        inputs: [
          {
            name: "orderbook_address",
            type: "core::starknet::contract_address::ContractAddress",
          },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "set_broker_fees",
        inputs: [
          { name: "fees_ratio", type: "ark_oz::erc2981::fees::FeesRatio" },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "get_broker_fees",
        inputs: [
          {
            name: "broker_address",
            type: "core::starknet::contract_address::ContractAddress",
          },
        ],
        outputs: [{ type: "ark_oz::erc2981::fees::FeesRatio" }],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "set_ark_fees",
        inputs: [
          { name: "fees_ratio", type: "ark_oz::erc2981::fees::FeesRatio" },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "get_ark_fees",
        inputs: [],
        outputs: [{ type: "ark_oz::erc2981::fees::FeesRatio" }],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "get_default_creator_fees",
        inputs: [],
        outputs: [
          {
            type: "(core::starknet::contract_address::ContractAddress, ark_oz::erc2981::fees::FeesRatio)",
          },
        ],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "set_default_creator_fees",
        inputs: [
          {
            name: "receiver",
            type: "core::starknet::contract_address::ContractAddress",
          },
          { name: "fees_ratio", type: "ark_oz::erc2981::fees::FeesRatio" },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "get_collection_creator_fees",
        inputs: [
          {
            name: "nft_address",
            type: "core::starknet::contract_address::ContractAddress",
          },
        ],
        outputs: [
          {
            type: "(core::starknet::contract_address::ContractAddress, ark_oz::erc2981::fees::FeesRatio)",
          },
        ],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "set_collection_creator_fees",
        inputs: [
          {
            name: "nft_address",
            type: "core::starknet::contract_address::ContractAddress",
          },
          {
            name: "receiver",
            type: "core::starknet::contract_address::ContractAddress",
          },
          { name: "fees_ratio", type: "ark_oz::erc2981::fees::FeesRatio" },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "get_fees_amount",
        inputs: [
          {
            name: "fulfill_broker",
            type: "core::starknet::contract_address::ContractAddress",
          },
          {
            name: "listing_broker",
            type: "core::starknet::contract_address::ContractAddress",
          },
          {
            name: "nft_address",
            type: "core::starknet::contract_address::ContractAddress",
          },
          { name: "nft_token_id", type: "core::integer::u256" },
          { name: "payment_amount", type: "core::integer::u256" },
        ],
        outputs: [{ type: "ark_starknet::interfaces::FeesAmount" }],
        state_mutability: "view",
      },
    ],
  },
  {
    type: "impl",
    name: "ExecutorUpgradeImpl",
    interface_name: "ark_starknet::interfaces::IUpgradable",
  },
  {
    type: "interface",
    name: "ark_starknet::interfaces::IUpgradable",
    items: [
      {
        type: "function",
        name: "upgrade",
        inputs: [
          { name: "class_hash", type: "core::starknet::class_hash::ClassHash" },
        ],
        outputs: [],
        state_mutability: "external",
      },
    ],
  },
  {
    type: "impl",
    name: "ExecutorMaintenanceImpl",
    interface_name: "ark_starknet::interfaces::IMaintenance",
  },
  {
    type: "enum",
    name: "core::bool",
    variants: [
      { name: "False", type: "()" },
      { name: "True", type: "()" },
    ],
  },
  {
    type: "interface",
    name: "ark_starknet::interfaces::IMaintenance",
    items: [
      {
        type: "function",
        name: "is_in_maintenance",
        inputs: [],
        outputs: [{ type: "core::bool" }],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "set_maintenance_mode",
        inputs: [{ name: "on", type: "core::bool" }],
        outputs: [],
        state_mutability: "external",
      },
    ],
  },
  {
    type: "constructor",
    name: "constructor",
    inputs: [
      {
        name: "admin_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "eth_contract_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      {
        name: "messaging_address",
        type: "core::starknet::contract_address::ContractAddress",
      },
      { name: "chain_id", type: "core::felt252" },
    ],
  },
  {
    type: "event",
    name: "ark_starknet::executor::executor::OrderExecuted",
    kind: "struct",
    members: [
      { name: "order_hash", type: "core::felt252", kind: "key" },
      { name: "transaction_hash", type: "core::felt252", kind: "key" },
      { name: "block_timestamp", type: "core::integer::u64", kind: "data" },
    ],
  },
  {
    type: "event",
    name: "ark_starknet::executor::executor::CollectionFallbackFees",
    kind: "struct",
    members: [
      {
        name: "collection",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "key",
      },
      { name: "amount", type: "core::integer::u256", kind: "key" },
      {
        name: "currency_contract",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
      {
        name: "receiver",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data",
      },
    ],
  },
  {
    type: "event",
    name: "ark_starknet::executor::executor::ExecutorInMaintenance",
    kind: "struct",
    members: [{ name: "on", type: "core::bool", kind: "data" }],
  },
  {
    type: "event",
    name: "ark_starknet::executor::executor::Event",
    kind: "enum",
    variants: [
      {
        name: "OrderExecuted",
        type: "ark_starknet::executor::executor::OrderExecuted",
        kind: "nested",
      },
      {
        name: "CollectionFallbackFees",
        type: "ark_starknet::executor::executor::CollectionFallbackFees",
        kind: "nested",
      },
      {
        name: "ExecutorInMaintenance",
        type: "ark_starknet::executor::executor::ExecutorInMaintenance",
        kind: "nested",
      },
    ],
  },
] as const;
