/**
 * This file is autogenerated by
 * You should not edit it manually or your changes might be overwritten.
 */

export default [
  {
    type: "impl",
    name: "ImplOrderbook",
    interface_name: "ark_orderbook::orderbook::Orderbook"
  },
  {
    type: "enum",
    name: "ark_common::protocol::order_types::OrderType",
    variants: [
      { name: "Listing", type: "()" },
      { name: "Auction", type: "()" },
      { name: "Offer", type: "()" },
      { name: "CollectionOffer", type: "()" }
    ]
  },
  {
    type: "enum",
    name: "ark_common::protocol::order_types::OrderStatus",
    variants: [
      { name: "Open", type: "()" },
      { name: "Fulfilled", type: "()" },
      { name: "Executed", type: "()" },
      { name: "CancelledUser", type: "()" },
      { name: "CancelledByNewOrder", type: "()" },
      { name: "CancelledAssetFault", type: "()" },
      { name: "CancelledOwnership", type: "()" }
    ]
  },
  {
    type: "enum",
    name: "ark_common::protocol::order_types::RouteType",
    variants: [
      { name: "Erc20ToErc721", type: "()" },
      { name: "Erc721ToErc20", type: "()" }
    ]
  },
  {
    type: "struct",
    name: "core::integer::u256",
    members: [
      { name: "low", type: "core::integer::u128" },
      { name: "high", type: "core::integer::u128" }
    ]
  },
  {
    type: "enum",
    name: "core::option::Option::<core::integer::u256>",
    variants: [
      { name: "Some", type: "core::integer::u256" },
      { name: "None", type: "()" }
    ]
  },
  {
    type: "struct",
    name: "core::array::Span::<core::felt252>",
    members: [
      { name: "snapshot", type: "@core::array::Array::<core::felt252>" }
    ]
  },
  {
    type: "struct",
    name: "ark_common::protocol::order_v1::OrderV1",
    members: [
      { name: "route", type: "ark_common::protocol::order_types::RouteType" },
      {
        name: "currency_address",
        type: "core::starknet::contract_address::ContractAddress"
      },
      { name: "currency_chain_id", type: "core::felt252" },
      { name: "salt", type: "core::felt252" },
      {
        name: "offerer",
        type: "core::starknet::contract_address::ContractAddress"
      },
      { name: "token_chain_id", type: "core::felt252" },
      {
        name: "token_address",
        type: "core::starknet::contract_address::ContractAddress"
      },
      { name: "token_id", type: "core::option::Option::<core::integer::u256>" },
      { name: "quantity", type: "core::integer::u256" },
      { name: "start_amount", type: "core::integer::u256" },
      { name: "end_amount", type: "core::integer::u256" },
      { name: "start_date", type: "core::integer::u64" },
      { name: "end_date", type: "core::integer::u64" },
      {
        name: "broker_id",
        type: "core::starknet::contract_address::ContractAddress"
      },
      { name: "additional_data", type: "core::array::Span::<core::felt252>" }
    ]
  },
  {
    type: "interface",
    name: "ark_orderbook::orderbook::Orderbook",
    items: [
      {
        type: "function",
        name: "get_order_type",
        inputs: [{ name: "order_hash", type: "core::felt252" }],
        outputs: [{ type: "ark_common::protocol::order_types::OrderType" }],
        state_mutability: "view"
      },
      {
        type: "function",
        name: "get_order_status",
        inputs: [{ name: "order_hash", type: "core::felt252" }],
        outputs: [{ type: "ark_common::protocol::order_types::OrderStatus" }],
        state_mutability: "view"
      },
      {
        type: "function",
        name: "get_auction_expiration",
        inputs: [{ name: "order_hash", type: "core::felt252" }],
        outputs: [{ type: "core::integer::u64" }],
        state_mutability: "view"
      },
      {
        type: "function",
        name: "get_order",
        inputs: [{ name: "order_hash", type: "core::felt252" }],
        outputs: [{ type: "ark_common::protocol::order_v1::OrderV1" }],
        state_mutability: "view"
      },
      {
        type: "function",
        name: "get_order_hash",
        inputs: [{ name: "token_hash", type: "core::felt252" }],
        outputs: [{ type: "core::felt252" }],
        state_mutability: "view"
      },
      {
        type: "function",
        name: "upgrade",
        inputs: [
          { name: "class_hash", type: "core::starknet::class_hash::ClassHash" }
        ],
        outputs: [],
        state_mutability: "external"
      },
      {
        type: "function",
        name: "update_starknet_executor_address",
        inputs: [
          {
            name: "value",
            type: "core::starknet::contract_address::ContractAddress"
          }
        ],
        outputs: [],
        state_mutability: "external"
      }
    ]
  },
  {
    type: "constructor",
    name: "constructor",
    inputs: [
      {
        name: "admin",
        type: "core::starknet::contract_address::ContractAddress"
      },
      { name: "chain_id", type: "core::felt252" }
    ]
  },
  {
    type: "struct",
    name: "ark_common::protocol::order_types::ExecutionValidationInfo",
    members: [
      { name: "order_hash", type: "core::felt252" },
      { name: "transaction_hash", type: "core::felt252" },
      { name: "starknet_block_timestamp", type: "core::integer::u64" },
      {
        name: "from",
        type: "core::starknet::contract_address::ContractAddress"
      },
      { name: "to", type: "core::starknet::contract_address::ContractAddress" }
    ]
  },
  {
    type: "struct",
    name: "ark_common::protocol::order_types::CancelInfo",
    members: [
      { name: "order_hash", type: "core::felt252" },
      {
        name: "canceller",
        type: "core::starknet::contract_address::ContractAddress"
      },
      { name: "token_chain_id", type: "core::felt252" },
      {
        name: "token_address",
        type: "core::starknet::contract_address::ContractAddress"
      },
      { name: "token_id", type: "core::option::Option::<core::integer::u256>" }
    ]
  },
  {
    type: "enum",
    name: "core::option::Option::<core::felt252>",
    variants: [
      { name: "Some", type: "core::felt252" },
      { name: "None", type: "()" }
    ]
  },
  {
    type: "struct",
    name: "ark_common::protocol::order_types::FulfillInfo",
    members: [
      { name: "order_hash", type: "core::felt252" },
      {
        name: "related_order_hash",
        type: "core::option::Option::<core::felt252>"
      },
      {
        name: "fulfiller",
        type: "core::starknet::contract_address::ContractAddress"
      },
      { name: "token_chain_id", type: "core::felt252" },
      {
        name: "token_address",
        type: "core::starknet::contract_address::ContractAddress"
      },
      { name: "token_id", type: "core::option::Option::<core::integer::u256>" },
      {
        name: "fulfill_broker_address",
        type: "core::starknet::contract_address::ContractAddress"
      }
    ]
  },
  {
    type: "event",
    name: "ark_orderbook::orderbook::orderbook::OrderPlaced",
    kind: "struct",
    members: [
      { name: "order_hash", type: "core::felt252", kind: "key" },
      { name: "order_version", type: "core::felt252", kind: "key" },
      {
        name: "order_type",
        type: "ark_common::protocol::order_types::OrderType",
        kind: "key"
      },
      {
        name: "cancelled_order_hash",
        type: "core::option::Option::<core::felt252>",
        kind: "data"
      },
      {
        name: "order",
        type: "ark_common::protocol::order_v1::OrderV1",
        kind: "data"
      }
    ]
  },
  {
    type: "event",
    name: "ark_orderbook::orderbook::orderbook::OrderExecuted",
    kind: "struct",
    members: [
      { name: "order_hash", type: "core::felt252", kind: "key" },
      {
        name: "order_status",
        type: "ark_common::protocol::order_types::OrderStatus",
        kind: "key"
      },
      { name: "version", type: "core::integer::u8", kind: "data" },
      { name: "transaction_hash", type: "core::felt252", kind: "data" },
      {
        name: "from",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data"
      },
      {
        name: "to",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "data"
      }
    ]
  },
  {
    type: "event",
    name: "ark_orderbook::orderbook::orderbook::OrderCancelled",
    kind: "struct",
    members: [
      { name: "order_hash", type: "core::felt252", kind: "key" },
      { name: "reason", type: "core::felt252", kind: "key" }
    ]
  },
  {
    type: "event",
    name: "ark_orderbook::orderbook::orderbook::RollbackStatus",
    kind: "struct",
    members: [
      { name: "order_hash", type: "core::felt252", kind: "key" },
      { name: "reason", type: "core::felt252", kind: "key" }
    ]
  },
  {
    type: "event",
    name: "ark_orderbook::orderbook::orderbook::OrderFulfilled",
    kind: "struct",
    members: [
      { name: "order_hash", type: "core::felt252", kind: "key" },
      {
        name: "fulfiller",
        type: "core::starknet::contract_address::ContractAddress",
        kind: "key"
      },
      {
        name: "related_order_hash",
        type: "core::option::Option::<core::felt252>",
        kind: "key"
      }
    ]
  },
  {
    type: "event",
    name: "ark_orderbook::orderbook::orderbook::Upgraded",
    kind: "struct",
    members: [
      {
        name: "class_hash",
        type: "core::starknet::class_hash::ClassHash",
        kind: "data"
      }
    ]
  },
  {
    type: "event",
    name: "ark_orderbook::orderbook::orderbook::Event",
    kind: "enum",
    variants: [
      {
        name: "OrderPlaced",
        type: "ark_orderbook::orderbook::orderbook::OrderPlaced",
        kind: "nested"
      },
      {
        name: "OrderExecuted",
        type: "ark_orderbook::orderbook::orderbook::OrderExecuted",
        kind: "nested"
      },
      {
        name: "OrderCancelled",
        type: "ark_orderbook::orderbook::orderbook::OrderCancelled",
        kind: "nested"
      },
      {
        name: "RollbackStatus",
        type: "ark_orderbook::orderbook::orderbook::RollbackStatus",
        kind: "nested"
      },
      {
        name: "OrderFulfilled",
        type: "ark_orderbook::orderbook::orderbook::OrderFulfilled",
        kind: "nested"
      },
      {
        name: "Upgraded",
        type: "ark_orderbook::orderbook::orderbook::Upgraded",
        kind: "nested"
      }
    ]
  }
] as const;
