/**
 * This file is autogenerated by
 * You should not edit it manually or your changes might be overwritten.
 */

export default [
  {
    type: "event",
    name: "solis::starknet_utils::starknet_utils::Event",
    kind: "enum",
    variants: []
  }
] as const;
