[package]
name = "ark_orderbook"
version = "0.1.0"

[dependencies]
ark_common = { path = "../ark_common" }
starknet = "2.5.4"

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true
