[package]
name = "ark_starknet"
version = "0.1.0"

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
ark_common = { path = "../ark_common" }
ark_component = { path = "../ark_component" }

ark_tokens = { path = "../ark_tokens" }
ark_oz = { path = "../ark_oz" }

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true

[scripts]
test.workspace = true

[tool]
fmt.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"
build-external-contracts = [
    "ark_tokens::erc20::FreeMintERC20",
    "ark_tokens::erc721::FreeMintNFT",
    "ark_tokens::erc721_royalty::FreeMintNFTRoyalty",
]
