[package]
name = "ark_starknet"
version = "0.1.0"

[dependencies]
starknet = "2.5.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }
ark_common = { path = "../ark_common" }
ark_tokens = { path = "../ark_tokens" }
ark_oz = { path = "../ark_oz" }

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"
build-external-contracts = [
    "ark_tokens::erc20::FreeMintERC20",
    "ark_tokens::erc721::FreeMintNFT",
    "ark_tokens::erc721_royalty::FreeMintNFTRoyalty",
]
