[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
cainome = { git = "https://github.com/cartridge-gg/cainome", tag = "v0.4.2", features = [
    "abigen-rs",
] }
num-bigint = "0.4.4"
starknet = "0.12.0"
