[package]
name = "ark_operator"
version = "0.1.0"

[dependencies]
starknet = ">=2.2.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.6.0" }

[[target.starknet-contract]]
sierra = true
casm = true
