[package]
name = "ark-db"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
anyhow = "1.0"
serde = "1.0.164"
log = "0.4"
ark-metadata = { path = "../ark-metadata" }
aws-sdk-dynamodb = "0.29.0"
dotenv = "0.15.0"
