import fs from "fs";
import path from "path";
import prettier from "prettier";
import type { CompiledSierra } from "starknet";

const TARGET_DIR = path.join(__dirname, "../artifacts");
const deploymentsDir = path.join(__dirname, "../contracts/target/dev");

const generatedContractComment = `/**
 * This file is autogenerated by
 * You should not edit it manually or your changes might be overwritten.
 */`;

//get all contracts with .contract_class.json
const contracts = fs.readdirSync(deploymentsDir).filter((file) =>
    file.endsWith(".contract_class.json")
);
console.log('\x1b[32m Generating ABI export... \x1b[0m')
contracts.forEach(async (contract) => {
    const contractPath = path.join(deploymentsDir, contract);
    const contractContent = fs.readFileSync(contractPath, "utf8");
    const contractData: CompiledSierra = JSON.parse(contractContent);
    const abi = JSON.stringify(contractData.abi.filter((item) => item.type !== "l1_handler"));

    if (!fs.existsSync(TARGET_DIR)) {
        fs.mkdirSync(TARGET_DIR);
    }

    const targetPath = path.join(TARGET_DIR, `${contract.replace(".contract_class.json", ".ts")}`);
    const fileContent = `${generatedContractComment}\n\nexport default ${abi} as const;`;
    fs.writeFileSync(targetPath, await prettier.format(fileContent, { parser: "typescript" }));
});

console.log(`\x1b[32m exported contract abi's to ${TARGET_DIR} \x1b[0m`);