[package]
name = "ark_tokens"
description = "StarkNet contracts for test tokens"
version = "0.1.0"

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
ark_oz = { path = "../ark_oz" }

[dev-dependencies]
snforge_std.workspace = true

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true
