name: ArkProject Deploy Contracts & Solis

on: workflow_dispatch

jobs:
  deploy-starknet:
    runs-on: ubuntu-latest
    name: Build & Deploy starknet contracts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.3.1

      - name: Build contracts
        run: |
          cd contracts
          scarb build --workspace

      - name: Install pnpm & dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Deploy orderbook contracts
        env:
          STARKNET_NODE_URL_GOERLI: ${{ secrets.STARKNET_NODE_URL_GOERLI }}
          SOLIS_NODE_URL_GOERLI: ${{ secrets.SOLIS_NODE_URL_GOERLI }}
          STARKNET_ADMIN_ADDRESS_GOERLI: ${{ secrets.STARKNET_ADMIN_ADDRESS_GOERLI }}
          STARKNET_ADMIN_PRIVATE_KEY_GOERLI: ${{ secrets.STARKNET_ADMIN_PRIVATE_KEY_GOERLI }}
          STARKNET_ADMIN_PUBLIC_KEY_GOERLI: ${{ secrets.STARKNET_ADMIN_PUBLIC_KEY_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_ADDRESS_GOERLI: ${{ secrets.STARKNET_SOLIS_ACCOUNT_ADDRESS_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_PRIVATE_KEY_GOERLI: ${{ secrets.STARKNET_SOLIS_ACCOUNT_PRIVATE_KEY_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_PUBLIC_KEY_GOERLI: ${{ secrets.STARKNET_SOLIS_ACCOUNT_PUBLIC_KEY_GOERLI }}
        run: |
          pnpm run deploy:starknet -- --starknet goerli
  deploy-solis:
    needs: deploy-starknet
    name: Deploy Solis latest image to Amazon ECS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: Install pnpm
        run: |
          npm install -g pnpm
          npm install -g aws-cdk
          pnpm install
      - name: Read environment variables from file
        id: vars
        run: |
          content=`cat contracts.json`
          STARKNET_APPCHAIN_MESSAGING_ADDRESS_GOERLI=$(echo $content | jq -r '.goerli.messaging')
          echo "STARKNET_APPCHAIN_MESSAGING_ADDRESS_GOERLI=$STARKNET_APPCHAIN_MESSAGING_ADDRESS_GOERLI" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          cd aws/cdk-solis-ecs
          pnpm install
      - name: Deploy CDK Stack Goerli
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          STARKNET_NODE_URL: ${{ secrets.STARKNET_NODE_URL_GOERLI }}
          STARKNET_APPCHAIN_MESSAGING_ADDRESS: ${{ env.STARKNET_APPCHAIN_MESSAGING_ADDRESS_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_ADDRESS: ${{ secrets.STARKNET_SOLIS_ACCOUNT_ADDRESS_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_PRIVATE_KEY: ${{ secrets.STARKNET_SOLIS_ACCOUNT_PRIVATE_KEY_GOERLI }}
        run: |
          cd aws/cdk-solis-ecs
          pnpm cdk deploy --all --require-approval never
  deploy-orderbook:
    needs: deploy-solis
    runs-on: ubuntu-latest
    name: Build & Deploy orderbook contract
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.3.1

      - name: Build contracts
        run: |
          cd contracts
          scarb build --workspace

      - name: Install pnpm & dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Deploy orderbook contracts
        env:
          STARKNET_NODE_URL_GOERLI: ${{ secrets.STARKNET_NODE_URL_GOERLI }}
          SOLIS_NODE_URL_GOERLI: ${{ secrets.SOLIS_NODE_URL_GOERLI }}
          STARKNET_ADMIN_ADDRESS_GOERLI: ${{ secrets.STARKNET_ADMIN_ADDRESS_GOERLI }}
          STARKNET_ADMIN_PRIVATE_KEY_GOERLI: ${{ secrets.STARKNET_ADMIN_PRIVATE_KEY_GOERLI }}
          STARKNET_ADMIN_PUBLIC_KEY_GOERLI: ${{ secrets.STARKNET_ADMIN_PUBLIC_KEY_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_ADDRESS_GOERLI: ${{ secrets.STARKNET_SOLIS_ACCOUNT_ADDRESS_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_PRIVATE_KEY_GOERLI: ${{ secrets.STARKNET_SOLIS_ACCOUNT_PRIVATE_KEY_GOERLI }}
          STARKNET_SOLIS_ACCOUNT_PUBLIC_KEY_GOERLI: ${{ secrets.STARKNET_SOLIS_ACCOUNT_PUBLIC_KEY_GOERLI }}
          SOLIS_ADMIN_ADDRESS_GOERLI: ${{ secrets.SOLIS_ADMIN_ADDRESS_GOERLI }}
          SOLIS_ADMIN_PRIVATE_KEY_GOERLI: ${{ secrets.SOLIS_ADMIN_PRIVATE_KEY_GOERLI }}
          SOLIS_ADMIN_PUBLIC_KEY_GOERLI: ${{ secrets.SOLIS_ADMIN_PUBLIC_KEY_GOERLI }}
        run: |
          pnpm run deploy:solis -- --solis goerli --starknet goerli
