name: Solis Build & Push Image to Amazon ECR

on:
  push:
    branches:
      - main
  # TODO: remove this once merged into main
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build-and-push-solis-image:
    runs-on: ubuntu-latest # This specifies the runner environment
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build Solis, tag, and push image to Amazon ECR
        run: |
          docker buildx create --use --name ecr-deploy-builder-solis
          docker buildx build --tag ${{ secrets.ECR_URL }}:solis-latest --file ./Dockerfile .
          docker push ${{ secrets.ECR_URL }}:solis-latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Change to CDK directory
        run: cd aws/cdk-solis-ecs

      - name: Install dependencies
        run: npm install

      - name: Deploy CDK Stack Goerli
        env:
          RPC_URL: ${{ secrets.RPC_URL_GOERLI }}
          MESSAGING_ADDRESS: ${{ secrets.MESSAGING_ADDRESS_GOERLI }}
          SENDER_ADDRESS: ${{ secrets.SENDER_ADDRESS_GOERLI }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_GOERLI }}
        run: npx cdk deploy --all --require-approval never
