name: clippy-action
on: [pull_request]

permissions:
  actions: read
  checks: write
  contents: write
  deployments: write
  id-token: write
  discussions: write
  pages: write
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy

      - uses: Swatinem/rust-cache@v2
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: scripts/clippy.sh
