name: clippy-action
on: [pull_request]

permissions:
  actions: read
  checks: write
  contents: write
  deployments: write
  id-token: write
  discussions: write
  pages: write
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: giraffate/clippy-action@v1
        with:
          reporter: "github-pr-review"
          github_token: ${{ secrets.GITHUB_TOKEN }}
