name: ArkChain contract testing

on:
  push:
    paths:
      - "contracts/**"
  pull_request:
    paths:
      - "contracts/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.3.1

      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v2
        with:
          starknet-foundry-version: 0.10.1Invalid order hash

      - name: Check Scarb Formatting
        run: cd contracts && scarb fmt --check

      - name: Test ark_common contracts
        run: cd contracts/ark_common && snforge test

      - name: Test ark_orderbook contracts
        run: cd contracts/ark_orderbook && snforge test

      - name: Test ark_starknet contracts
        run: cd contracts/ark_starknet && scarb test

      - name: Test ark_tokens contracts
        run: cd contracts/ark_tokens && scarb test
