name: ArkChain contract testing

on:
  push:
    paths:
      - "crates/ark-contracts/arkchain/**"
  pull_request:
    paths:
      - "crates/ark-contracts/arkchain/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.3.1

      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v2
        with:
          starknet-foundry-version: 0.10.1

      - name: Check Scarb Formatting
        run: cd crates/ark-contracts/arkchain && scarb fmt --check

      - name: Run Snforge Tests
        run: cd crates/ark-contracts/arkchain && snforge test
